from EdennCode.ModelFactory.MusicGenModelFactory.CloudMusicGen.base import MusicProvider
from EdennCode.ModelFactory.MusicGenModelFactory.CloudMusicGen.provider_a_wrapper import ProviderAMusicProvider
from EdennCode.ModelFactory.MusicGenModelFactory.CloudMusicGen.provider_b_music import ProviderBMusicProvider
from EdennCode.ModelFactory.MusicGenModelFactory.CloudMusicGen.provider_c import ProviderCApi
