from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from EdennCode.Util.MediaUtils.ffmpeg_utils import resolve_ffmpeg_binary


WATERMARK_TEXT = "generated by Edenn Multimodal Perceptron 1.0"


def _audio_codec_args(path: Path) -> list[str]:
    suffix = path.suffix.lower()
    if suffix == ".wav":
        return ["-c:a", "pcm_s16le"]
    if suffix == ".mp3":
        return ["-c:a", "libmp3lame", "-b:a", "192k"]
    if suffix in {".m4a", ".mp4", ".aac"}:
        return ["-c:a", "aac", "-b:a", "192k"]
    return ["-c:a", "aac", "-b:a", "192k"]


def _watermarked_path(audio_path: Path) -> Path:
    suffix = audio_path.suffix or ".wav"
    if audio_path.stem.endswith("_watermarked"):
        return audio_path
    return audio_path.with_name(f"{audio_path.stem}_watermarked{suffix}")


def _generate_watermark_voice_clip(output_path: Path) -> Path:
    if output_path.exists() and output_path.stat().st_size > 0:
        return output_path

    output_path.parent.mkdir(parents=True, exist_ok=True)

    model = os.getenv("EDENN_WATERMARK_TTS_MODEL", "speech-standard")
    voice = os.getenv("EDENN_WATERMARK_TTS_VOICE", "shimmer")
    instructions = os.getenv(
        "EDENN_WATERMARK_TTS_INSTRUCTIONS",
        "Speak clearly and briefly in a neutral studio voice.",
    )
    speed = float(os.getenv("EDENN_WATERMARK_TTS_SPEED", "1.0"))

    azure_key = os.getenv("SPEECH_GATEWAY_API_KEY", "").strip()
    azure_endpoint = os.getenv("SPEECH_GATEWAY_ENDPOINT", "").strip()
    azure_version = os.getenv("SPEECH_GATEWAY_API_VERSION", "").strip()

    if azure_key and azure_endpoint and azure_version:
        from EdennCode.ModelFactory.LanguageModelFactory.gateway_clients import (
            make_gateway_client,
        )

        client = make_gateway_client(
            endpoint=azure_endpoint,
            api_key=azure_key,
            api_version=azure_version,
        )
    elif os.getenv("MODEL_GATEWAY_API_KEY", "").strip():
        from EdennCode.ModelFactory.LanguageModelFactory.gateway_clients import (
            make_direct_client,
        )

        client = make_direct_client()
    else:
        raise RuntimeError(
            "water_mark=True requires TTS credentials. Set SPEECH_GATEWAY_API_KEY, "
            "SPEECH_GATEWAY_ENDPOINT, SPEECH_GATEWAY_API_VERSION, or MODEL_GATEWAY_API_KEY."
        )

    with client.audio.speech.with_streaming_response.create(
        model=model,
        voice=voice,
        input=WATERMARK_TEXT,
        instructions=instructions,
        speed=speed,
        response_format="wav",
    ) as response:
        response.stream_to_file(str(output_path))

    return output_path


def _copy_lyrics_sidecar(source_path: Path, target_path: Path) -> None:
    source_lyrics = source_path.with_suffix(".lyrics.txt")
    if not source_lyrics.exists():
        return
    target_lyrics = target_path.with_suffix(".lyrics.txt")
    shutil.copyfile(source_lyrics, target_lyrics)


def append_voice_watermark_to_audio(audio_path: Path) -> Path:
    """Append the Edenn spoken watermark clip to a full-track audio file."""

    audio_path = Path(audio_path)
    if audio_path.stem.endswith("_watermarked"):
        return audio_path
    if not audio_path.exists():
        raise FileNotFoundError(audio_path)

    output_path = _watermarked_path(audio_path)
    if output_path.exists() and output_path.stat().st_size > 0:
        return output_path

    clip_path = _generate_watermark_voice_clip(
        audio_path.parent / "edenn_watermark_voice.wav"
    )
    ffmpeg_bin = resolve_ffmpeg_binary()
    filter_complex = (
        "[0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo[a0];"
        "[1:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo[a1];"
        "[a0][a1]concat=n=2:v=0:a=1[aout]"
    )
    cmd = [
        ffmpeg_bin,
        "-y",
        "-i",
        str(audio_path),
        "-i",
        str(clip_path),
        "-filter_complex",
        filter_complex,
        "-map",
        "[aout]",
        "-vn",
        *_audio_codec_args(output_path),
        str(output_path),
    ]
    subprocess.run(cmd, check=True, capture_output=True, text=True)
    _copy_lyrics_sidecar(audio_path, output_path)
    return output_path


__all__ = ["WATERMARK_TEXT", "append_voice_watermark_to_audio"]
